insert into mimetypes (mime_type, ext) values ('application/andrew-inset', 'ez')
insert into mimetypes (mime_type, ext) values ('application/applixware', 'aw')
insert into mimetypes (mime_type, ext) values ('application/atom+xml', 'atom')
insert into mimetypes (mime_type, ext) values ('application/atomcat+xml', 'atomcat')
insert into mimetypes (mime_type, ext) values ('application/atomsvc+xml', 'atomsvc')
insert into mimetypes (mime_type, ext) values ('application/ccxml+xml', 'ccxml')
insert into mimetypes (mime_type, ext) values ('application/cdmi-capability', 'cdmia')
insert into mimetypes (mime_type, ext) values ('application/cdmi-container', 'cdmic')
insert into mimetypes (mime_type, ext) values ('application/cdmi-domain', 'cdmid')
insert into mimetypes (mime_type, ext) values ('application/cdmi-object', 'cdmio')
insert into mimetypes (mime_type, ext) values ('application/cdmi-queue', 'cdmiq')
insert into mimetypes (mime_type, ext) values ('application/cu-seeme', 'cu')
insert into mimetypes (mime_type, ext) values ('application/davmount+xml', 'davmount')
insert into mimetypes (mime_type, ext) values ('application/docbook+xml', 'dbk')
insert into mimetypes (mime_type, ext) values ('application/dssc+der', 'dssc')
insert into mimetypes (mime_type, ext) values ('application/dssc+xml', 'xdssc')
insert into mimetypes (mime_type, ext) values ('application/ecmascript', 'ecma')
insert into mimetypes (mime_type, ext) values ('application/emma+xml', 'emma')
insert into mimetypes (mime_type, ext) values ('application/epub+zip', 'epub')
insert into mimetypes (mime_type, ext) values ('application/exi', 'exi')
insert into mimetypes (mime_type, ext) values ('application/font-tdpfr', 'pfr')
insert into mimetypes (mime_type, ext) values ('application/gml+xml', 'gml')
insert into mimetypes (mime_type, ext) values ('application/gpx+xml', 'gpx')
insert into mimetypes (mime_type, ext) values ('application/gxf', 'gxf')
insert into mimetypes (mime_type, ext) values ('application/hyperstudio', 'stk')
insert into mimetypes (mime_type, ext) values ('application/inkml+xml', 'ink inkml')
insert into mimetypes (mime_type, ext) values ('application/ipfix', 'ipfix')
insert into mimetypes (mime_type, ext) values ('application/java-archive', 'jar')
insert into mimetypes (mime_type, ext) values ('application/java-serialized-object', 'ser')
insert into mimetypes (mime_type, ext) values ('application/java-vm', 'class')
insert into mimetypes (mime_type, ext) values ('application/javascript', 'js')
insert into mimetypes (mime_type, ext) values ('application/json', 'json')
insert into mimetypes (mime_type, ext) values ('application/jsonml+json', 'jsonml')
insert into mimetypes (mime_type, ext) values ('application/lost+xml', 'lostxml')
insert into mimetypes (mime_type, ext) values ('application/mac-binhex40', 'hqx')
insert into mimetypes (mime_type, ext) values ('application/mac-compactpro', 'cpt')
insert into mimetypes (mime_type, ext) values ('application/mads+xml', 'mads')
insert into mimetypes (mime_type, ext) values ('application/marc', 'mrc')
insert into mimetypes (mime_type, ext) values ('application/marcxml+xml', 'mrcx')
insert into mimetypes (mime_type, ext) values ('application/mathematica', 'ma nb mb')
insert into mimetypes (mime_type, ext) values ('application/mathml+xml', 'mathml')
insert into mimetypes (mime_type, ext) values ('application/mbox', 'mbox')
insert into mimetypes (mime_type, ext) values ('application/mediaservercontrol+xml', 'mscml')
insert into mimetypes (mime_type, ext) values ('application/metalink+xml', 'metalink')
insert into mimetypes (mime_type, ext) values ('application/metalink4+xml', 'meta4')
insert into mimetypes (mime_type, ext) values ('application/mets+xml', 'mets')
insert into mimetypes (mime_type, ext) values ('application/mods+xml', 'mods')
insert into mimetypes (mime_type, ext) values ('application/mp21', 'm21 mp21')
insert into mimetypes (mime_type, ext) values ('application/mp4', 'mp4s')
insert into mimetypes (mime_type, ext) values ('application/msword', 'doc dot')
insert into mimetypes (mime_type, ext) values ('application/mxf', 'mxf')
insert into mimetypes (mime_type, ext) values ('application/octet-stream', 'bin dms lrf mar so dist distz pkg bpk dump elc deploy')
insert into mimetypes (mime_type, ext) values ('application/oda', 'oda')
insert into mimetypes (mime_type, ext) values ('application/oebps-package+xml', 'opf')
insert into mimetypes (mime_type, ext) values ('application/ogg', 'ogx')
insert into mimetypes (mime_type, ext) values ('application/omdoc+xml', 'omdoc')
insert into mimetypes (mime_type, ext) values ('application/onenote', 'onetoc onetoc2 onetmp onepkg')
insert into mimetypes (mime_type, ext) values ('application/oxps', 'oxps')
insert into mimetypes (mime_type, ext) values ('application/patch-ops-error+xml', 'xer')
insert into mimetypes (mime_type, ext) values ('application/pdf', 'pdf')
insert into mimetypes (mime_type, ext) values ('application/pgp-encrypted', 'pgp')
insert into mimetypes (mime_type, ext) values ('application/pgp-signature', 'asc sig')
insert into mimetypes (mime_type, ext) values ('application/pics-rules', 'prf')
insert into mimetypes (mime_type, ext) values ('application/pkcs10', 'p10')
insert into mimetypes (mime_type, ext) values ('application/pkcs7-mime', 'p7m p7c')
insert into mimetypes (mime_type, ext) values ('application/pkcs7-signature', 'p7s')
insert into mimetypes (mime_type, ext) values ('application/pkcs8', 'p8')
insert into mimetypes (mime_type, ext) values ('application/pkix-attr-cert', 'ac')
insert into mimetypes (mime_type, ext) values ('application/pkix-cert', 'cer')
insert into mimetypes (mime_type, ext) values ('application/pkix-crl', 'crl')
insert into mimetypes (mime_type, ext) values ('application/pkix-pkipath', 'pkipath')
insert into mimetypes (mime_type, ext) values ('application/pkixcmp', 'pki')
insert into mimetypes (mime_type, ext) values ('application/pls+xml', 'pls')
insert into mimetypes (mime_type, ext) values ('application/postscript', 'ai eps ps')
insert into mimetypes (mime_type, ext) values ('application/prs.cww', 'cww')
insert into mimetypes (mime_type, ext) values ('application/pskc+xml', 'pskcxml')
insert into mimetypes (mime_type, ext) values ('application/rdf+xml', 'rdf')
insert into mimetypes (mime_type, ext) values ('application/reginfo+xml', 'rif')
insert into mimetypes (mime_type, ext) values ('application/relax-ng-compact-syntax', 'rnc')
insert into mimetypes (mime_type, ext) values ('application/resource-lists+xml', 'rl')
insert into mimetypes (mime_type, ext) values ('application/resource-lists-diff+xml', 'rld')
insert into mimetypes (mime_type, ext) values ('application/rls-services+xml', 'rs')
insert into mimetypes (mime_type, ext) values ('application/rpki-ghostbusters', 'gbr')
insert into mimetypes (mime_type, ext) values ('application/rpki-manifest', 'mft')
insert into mimetypes (mime_type, ext) values ('application/rpki-roa', 'roa')
insert into mimetypes (mime_type, ext) values ('application/rsd+xml', 'rsd')
insert into mimetypes (mime_type, ext) values ('application/rss+xml', 'rss')
insert into mimetypes (mime_type, ext) values ('application/rtf', 'rtf')
insert into mimetypes (mime_type, ext) values ('application/sbml+xml', 'sbml')
insert into mimetypes (mime_type, ext) values ('application/scvp-cv-request', 'scq')
insert into mimetypes (mime_type, ext) values ('application/scvp-cv-response', 'scs')
insert into mimetypes (mime_type, ext) values ('application/scvp-vp-request', 'spq')
insert into mimetypes (mime_type, ext) values ('application/scvp-vp-response', 'spp')
insert into mimetypes (mime_type, ext) values ('application/sdp', 'sdp')
insert into mimetypes (mime_type, ext) values ('application/set-payment-initiation', 'setpay')
insert into mimetypes (mime_type, ext) values ('application/set-registration-initiation', 'setreg')
insert into mimetypes (mime_type, ext) values ('application/shf+xml', 'shf')
insert into mimetypes (mime_type, ext) values ('application/smil+xml', 'smi smil')
insert into mimetypes (mime_type, ext) values ('application/sparql-query', 'rq')
insert into mimetypes (mime_type, ext) values ('application/sparql-results+xml', 'srx')
insert into mimetypes (mime_type, ext) values ('application/srgs', 'gram')
insert into mimetypes (mime_type, ext) values ('application/srgs+xml', 'grxml')
insert into mimetypes (mime_type, ext) values ('application/sru+xml', 'sru')
insert into mimetypes (mime_type, ext) values ('application/ssdl+xml', 'ssdl')
insert into mimetypes (mime_type, ext) values ('application/ssml+xml', 'ssml')
insert into mimetypes (mime_type, ext) values ('application/tei+xml', 'tei teicorpus')
insert into mimetypes (mime_type, ext) values ('application/thraud+xml', 'tfi')
insert into mimetypes (mime_type, ext) values ('application/timestamped-data', 'tsd')
insert into mimetypes (mime_type, ext) values ('application/vnd.3gpp.pic-bw-large', 'plb')
insert into mimetypes (mime_type, ext) values ('application/vnd.3gpp.pic-bw-small', 'psb')
insert into mimetypes (mime_type, ext) values ('application/vnd.3gpp.pic-bw-var', 'pvb')
insert into mimetypes (mime_type, ext) values ('application/vnd.3gpp2.tcap', 'tcap')
insert into mimetypes (mime_type, ext) values ('application/vnd.3m.post-it-notes', 'pwn')
insert into mimetypes (mime_type, ext) values ('application/vnd.accpac.simply.aso', 'aso')
insert into mimetypes (mime_type, ext) values ('application/vnd.accpac.simply.imp', 'imp')
insert into mimetypes (mime_type, ext) values ('application/vnd.acucobol', 'acu')
insert into mimetypes (mime_type, ext) values ('application/vnd.acucorp', 'atc acutc')
insert into mimetypes (mime_type, ext) values ('application/vnd.adobe.air-application-installer-package+zip', 'air')
insert into mimetypes (mime_type, ext) values ('application/vnd.adobe.formscentral.fcdt', 'fcdt')
insert into mimetypes (mime_type, ext) values ('application/vnd.adobe.fxp', 'fxp fxpl')
insert into mimetypes (mime_type, ext) values ('application/vnd.adobe.xdp+xml', 'xdp')
insert into mimetypes (mime_type, ext) values ('application/vnd.adobe.xfdf', 'xfdf')
insert into mimetypes (mime_type, ext) values ('application/vnd.ahead.space', 'ahead')
insert into mimetypes (mime_type, ext) values ('application/vnd.airzip.filesecure.azf', 'azf')
insert into mimetypes (mime_type, ext) values ('application/vnd.airzip.filesecure.azs', 'azs')
insert into mimetypes (mime_type, ext) values ('application/vnd.amazon.ebook', 'azw')
insert into mimetypes (mime_type, ext) values ('application/vnd.americandynamics.acc', 'acc')
insert into mimetypes (mime_type, ext) values ('application/vnd.amiga.ami', 'ami')
insert into mimetypes (mime_type, ext) values ('application/vnd.android.package-archive', 'apk')
insert into mimetypes (mime_type, ext) values ('application/vnd.anser-web-certificate-issue-initiation', 'cii')
insert into mimetypes (mime_type, ext) values ('application/vnd.anser-web-funds-transfer-initiation', 'fti')
insert into mimetypes (mime_type, ext) values ('application/vnd.antix.game-component', 'atx')
insert into mimetypes (mime_type, ext) values ('application/vnd.apple.installer+xml', 'mpkg')
insert into mimetypes (mime_type, ext) values ('application/vnd.apple.mpegurl', 'm3u8')
insert into mimetypes (mime_type, ext) values ('application/vnd.aristanetworks.swi', 'swi')
insert into mimetypes (mime_type, ext) values ('application/vnd.astraea-software.iota', 'iota')
insert into mimetypes (mime_type, ext) values ('application/vnd.audiograph', 'aep')
insert into mimetypes (mime_type, ext) values ('application/vnd.blueice.multipass', 'mpm')
insert into mimetypes (mime_type, ext) values ('application/vnd.bmi', 'bmi')
insert into mimetypes (mime_type, ext) values ('application/vnd.businessobjects', 'rep')
insert into mimetypes (mime_type, ext) values ('application/vnd.chemdraw+xml', 'cdxml')
insert into mimetypes (mime_type, ext) values ('application/vnd.chipnuts.karaoke-mmd', 'mmd')
insert into mimetypes (mime_type, ext) values ('application/vnd.cinderella', 'cdy')
insert into mimetypes (mime_type, ext) values ('application/vnd.claymore', 'cla')
insert into mimetypes (mime_type, ext) values ('application/vnd.cloanto.rp9', 'rp9')
insert into mimetypes (mime_type, ext) values ('application/vnd.clonk.c4group', 'c4g c4d c4f c4p c4u')
insert into mimetypes (mime_type, ext) values ('application/vnd.cluetrust.cartomobile-config', 'c11amc')
insert into mimetypes (mime_type, ext) values ('application/vnd.cluetrust.cartomobile-config-pkg', 'c11amz')
insert into mimetypes (mime_type, ext) values ('application/vnd.commonspace', 'csp')
insert into mimetypes (mime_type, ext) values ('application/vnd.contact.cmsg', 'cdbcmsg')
insert into mimetypes (mime_type, ext) values ('application/vnd.cosmocaller', 'cmc')
insert into mimetypes (mime_type, ext) values ('application/vnd.crick.clicker', 'clkx')
insert into mimetypes (mime_type, ext) values ('application/vnd.crick.clicker.keyboard', 'clkk')
insert into mimetypes (mime_type, ext) values ('application/vnd.crick.clicker.palette', 'clkp')
insert into mimetypes (mime_type, ext) values ('application/vnd.crick.clicker.template', 'clkt')
insert into mimetypes (mime_type, ext) values ('application/vnd.crick.clicker.wordbank', 'clkw')
insert into mimetypes (mime_type, ext) values ('application/vnd.criticaltools.wbs+xml', 'wbs')
insert into mimetypes (mime_type, ext) values ('application/vnd.ctc-posml', 'pml')
insert into mimetypes (mime_type, ext) values ('application/vnd.cups-ppd', 'ppd')
insert into mimetypes (mime_type, ext) values ('application/vnd.curl.car', 'car')
insert into mimetypes (mime_type, ext) values ('application/vnd.curl.pcurl', 'pcurl')
insert into mimetypes (mime_type, ext) values ('application/vnd.dart', 'dart')
insert into mimetypes (mime_type, ext) values ('application/vnd.data-vision.rdz', 'rdz')
insert into mimetypes (mime_type, ext) values ('application/vnd.dece.data', 'uvf uvvf uvd uvvd')
insert into mimetypes (mime_type, ext) values ('application/vnd.dece.ttml+xml', 'uvt uvvt')
insert into mimetypes (mime_type, ext) values ('application/vnd.dece.unspecified', 'uvx uvvx')
insert into mimetypes (mime_type, ext) values ('application/vnd.dece.zip', 'uvz uvvz')
insert into mimetypes (mime_type, ext) values ('application/vnd.denovo.fcselayout-link', 'fe_launch')
insert into mimetypes (mime_type, ext) values ('application/vnd.dna', 'dna')
insert into mimetypes (mime_type, ext) values ('application/vnd.dolby.mlp', 'mlp')
insert into mimetypes (mime_type, ext) values ('application/vnd.dpgraph', 'dpg')
insert into mimetypes (mime_type, ext) values ('application/vnd.dreamfactory', 'dfac')
insert into mimetypes (mime_type, ext) values ('application/vnd.ds-keypoint', 'kpxx')
insert into mimetypes (mime_type, ext) values ('application/vnd.dvb.ait', 'ait')
insert into mimetypes (mime_type, ext) values ('application/vnd.dvb.service', 'svc')
insert into mimetypes (mime_type, ext) values ('application/vnd.dynageo', 'geo')
insert into mimetypes (mime_type, ext) values ('application/vnd.ecowin.chart', 'mag')
insert into mimetypes (mime_type, ext) values ('application/vnd.enliven', 'nml')
insert into mimetypes (mime_type, ext) values ('application/vnd.epson.esf', 'esf')
insert into mimetypes (mime_type, ext) values ('application/vnd.epson.msf', 'msf')
insert into mimetypes (mime_type, ext) values ('application/vnd.epson.quickanime', 'qam')
insert into mimetypes (mime_type, ext) values ('application/vnd.epson.salt', 'slt')
insert into mimetypes (mime_type, ext) values ('application/vnd.epson.ssf', 'ssf')
insert into mimetypes (mime_type, ext) values ('application/vnd.eszigno3+xml', 'es3 et3')
insert into mimetypes (mime_type, ext) values ('application/vnd.ezpix-album', 'ez2')
insert into mimetypes (mime_type, ext) values ('application/vnd.ezpix-package', 'ez3')
insert into mimetypes (mime_type, ext) values ('application/vnd.fdf', 'fdf')
insert into mimetypes (mime_type, ext) values ('application/vnd.fdsn.mseed', 'mseed')
insert into mimetypes (mime_type, ext) values ('application/vnd.fdsn.seed', 'seed dataless')
insert into mimetypes (mime_type, ext) values ('application/vnd.flographit', 'gph')
insert into mimetypes (mime_type, ext) values ('application/vnd.fluxtime.clip', 'ftc')
insert into mimetypes (mime_type, ext) values ('application/vnd.framemaker', 'fm frame maker book')
insert into mimetypes (mime_type, ext) values ('application/vnd.frogans.fnc', 'fnc')
insert into mimetypes (mime_type, ext) values ('application/vnd.frogans.ltf', 'ltf')
insert into mimetypes (mime_type, ext) values ('application/vnd.fsc.weblaunch', 'fsc')
insert into mimetypes (mime_type, ext) values ('application/vnd.fujitsu.oasys', 'oas')
insert into mimetypes (mime_type, ext) values ('application/vnd.fujitsu.oasys2', 'oa2')
insert into mimetypes (mime_type, ext) values ('application/vnd.fujitsu.oasys3', 'oa3')
insert into mimetypes (mime_type, ext) values ('application/vnd.fujitsu.oasysgp', 'fg5')
insert into mimetypes (mime_type, ext) values ('application/vnd.fujitsu.oasysprs', 'bh2')
insert into mimetypes (mime_type, ext) values ('application/vnd.fujixerox.ddd', 'ddd')
insert into mimetypes (mime_type, ext) values ('application/vnd.fujixerox.docuworks', 'xdw')
insert into mimetypes (mime_type, ext) values ('application/vnd.fujixerox.docuworks.binder', 'xbd')
insert into mimetypes (mime_type, ext) values ('application/vnd.fuzzysheet', 'fzs')
insert into mimetypes (mime_type, ext) values ('application/vnd.genomatix.tuxedo', 'txd')
insert into mimetypes (mime_type, ext) values ('application/vnd.geogebra.file', 'ggb')
insert into mimetypes (mime_type, ext) values ('application/vnd.geogebra.tool', 'ggt')
insert into mimetypes (mime_type, ext) values ('application/vnd.geometry-explorer', 'gex gre')
insert into mimetypes (mime_type, ext) values ('application/vnd.geonext', 'gxt')
insert into mimetypes (mime_type, ext) values ('application/vnd.geoplan', 'g2w')
insert into mimetypes (mime_type, ext) values ('application/vnd.geospace', 'g3w')
insert into mimetypes (mime_type, ext) values ('application/vnd.gmx', 'gmx')
insert into mimetypes (mime_type, ext) values ('application/vnd.google-earth.kml+xml', 'kml')
insert into mimetypes (mime_type, ext) values ('application/vnd.google-earth.kmz', 'kmz')
insert into mimetypes (mime_type, ext) values ('application/vnd.grafeq', 'gqf gqs')
insert into mimetypes (mime_type, ext) values ('application/vnd.groove-account', 'gac')
insert into mimetypes (mime_type, ext) values ('application/vnd.groove-help', 'ghf')
insert into mimetypes (mime_type, ext) values ('application/vnd.groove-identity-message', 'gim')
insert into mimetypes (mime_type, ext) values ('application/vnd.groove-injector', 'grv')
insert into mimetypes (mime_type, ext) values ('application/vnd.groove-tool-message', 'gtm')
insert into mimetypes (mime_type, ext) values ('application/vnd.groove-tool-template', 'tpl')
insert into mimetypes (mime_type, ext) values ('application/vnd.groove-vcard', 'vcg')
insert into mimetypes (mime_type, ext) values ('application/vnd.hal+xml', 'hal')
insert into mimetypes (mime_type, ext) values ('application/vnd.handheld-entertainment+xml', 'zmm')
insert into mimetypes (mime_type, ext) values ('application/vnd.hbci', 'hbci')
insert into mimetypes (mime_type, ext) values ('application/vnd.hhe.lesson-player', 'les')
insert into mimetypes (mime_type, ext) values ('application/vnd.hp-hpgl', 'hpgl')
insert into mimetypes (mime_type, ext) values ('application/vnd.hp-hpid', 'hpid')
insert into mimetypes (mime_type, ext) values ('application/vnd.hp-hps', 'hps')
insert into mimetypes (mime_type, ext) values ('application/vnd.hp-jlyt', 'jlt')
insert into mimetypes (mime_type, ext) values ('application/vnd.hp-pcl', 'pcl')
insert into mimetypes (mime_type, ext) values ('application/vnd.hp-pclxl', 'pclxl')
insert into mimetypes (mime_type, ext) values ('application/vnd.hydrostatix.sof-data', 'sfd-hdstx')
insert into mimetypes (mime_type, ext) values ('application/vnd.ibm.minipay', 'mpy')
insert into mimetypes (mime_type, ext) values ('application/vnd.ibm.modcap', 'afp listafp list3820')
insert into mimetypes (mime_type, ext) values ('application/vnd.ibm.rights-management', 'irm')
insert into mimetypes (mime_type, ext) values ('application/vnd.ibm.secure-container', 'sc')
insert into mimetypes (mime_type, ext) values ('application/vnd.iccprofile', 'icc icm')
insert into mimetypes (mime_type, ext) values ('application/vnd.igloader', 'igl')
insert into mimetypes (mime_type, ext) values ('application/vnd.immervision-ivp', 'ivp')
insert into mimetypes (mime_type, ext) values ('application/vnd.immervision-ivu', 'ivu')
insert into mimetypes (mime_type, ext) values ('application/vnd.insors.igm', 'igm')
insert into mimetypes (mime_type, ext) values ('application/vnd.intercon.formnet', 'xpw xpx')
insert into mimetypes (mime_type, ext) values ('application/vnd.intergeo', 'i2g')
insert into mimetypes (mime_type, ext) values ('application/vnd.intu.qbo', 'qbo')
insert into mimetypes (mime_type, ext) values ('application/vnd.intu.qfx', 'qfx')
insert into mimetypes (mime_type, ext) values ('application/vnd.ipunplugged.rcprofile', 'rcprofile')
insert into mimetypes (mime_type, ext) values ('application/vnd.irepository.package+xml', 'irp')
insert into mimetypes (mime_type, ext) values ('application/vnd.is-xpr', 'xpr')
insert into mimetypes (mime_type, ext) values ('application/vnd.isac.fcs', 'fcs')
insert into mimetypes (mime_type, ext) values ('application/vnd.jam', 'jam')
insert into mimetypes (mime_type, ext) values ('application/vnd.jcp.javame.midlet-rms', 'rms')
insert into mimetypes (mime_type, ext) values ('application/vnd.jisp', 'jisp')
insert into mimetypes (mime_type, ext) values ('application/vnd.joost.joda-archive', 'joda')
insert into mimetypes (mime_type, ext) values ('application/vnd.kahootz', 'ktz ktr')
insert into mimetypes (mime_type, ext) values ('application/vnd.kde.karbon', 'karbon')
insert into mimetypes (mime_type, ext) values ('application/vnd.kde.kchart', 'chrt')
insert into mimetypes (mime_type, ext) values ('application/vnd.kde.kformula', 'kfo')
insert into mimetypes (mime_type, ext) values ('application/vnd.kde.kivio', 'flw')
insert into mimetypes (mime_type, ext) values ('application/vnd.kde.kontour', 'kon')
insert into mimetypes (mime_type, ext) values ('application/vnd.kde.kpresenter', 'kpr kpt')
insert into mimetypes (mime_type, ext) values ('application/vnd.kde.kspread', 'ksp')
insert into mimetypes (mime_type, ext) values ('application/vnd.kde.kword', 'kwd kwt')
insert into mimetypes (mime_type, ext) values ('application/vnd.kenameaapp', 'htke')
insert into mimetypes (mime_type, ext) values ('application/vnd.kidspiration', 'kia')
insert into mimetypes (mime_type, ext) values ('application/vnd.kinar', 'kne knp')
insert into mimetypes (mime_type, ext) values ('application/vnd.koan', 'skp skd skt skm')
insert into mimetypes (mime_type, ext) values ('application/vnd.kodak-descriptor', 'sse')
insert into mimetypes (mime_type, ext) values ('application/vnd.las.las+xml', 'lasxml')
insert into mimetypes (mime_type, ext) values ('application/vnd.llamagraphics.life-balance.desktop', 'lbd')
insert into mimetypes (mime_type, ext) values ('application/vnd.llamagraphics.life-balance.exchange+xml', 'lbe')
insert into mimetypes (mime_type, ext) values ('application/vnd.lotus-1-2-3', '123')
insert into mimetypes (mime_type, ext) values ('application/vnd.lotus-approach', 'apr')
insert into mimetypes (mime_type, ext) values ('application/vnd.lotus-freelance', 'pre')
insert into mimetypes (mime_type, ext) values ('application/vnd.lotus-notes', 'nsf')
insert into mimetypes (mime_type, ext) values ('application/vnd.lotus-organizer', 'org')
insert into mimetypes (mime_type, ext) values ('application/vnd.lotus-screencam', 'scm')
insert into mimetypes (mime_type, ext) values ('application/vnd.lotus-wordpro', 'lwp')
insert into mimetypes (mime_type, ext) values ('application/vnd.macports.portpkg', 'portpkg')
insert into mimetypes (mime_type, ext) values ('application/vnd.mcd', 'mcd')
insert into mimetypes (mime_type, ext) values ('application/vnd.medcalcdata', 'mc1')
insert into mimetypes (mime_type, ext) values ('application/vnd.mediastation.cdkey', 'cdkey')
insert into mimetypes (mime_type, ext) values ('application/vnd.mfer', 'mwf')
insert into mimetypes (mime_type, ext) values ('application/vnd.mfmp', 'mfm')
insert into mimetypes (mime_type, ext) values ('application/vnd.micrografx.flo', 'flo')
insert into mimetypes (mime_type, ext) values ('application/vnd.micrografx.igx', 'igx')
insert into mimetypes (mime_type, ext) values ('application/vnd.mif', 'mif')
insert into mimetypes (mime_type, ext) values ('application/vnd.mobius.daf', 'daf')
insert into mimetypes (mime_type, ext) values ('application/vnd.mobius.dis', 'dis')
insert into mimetypes (mime_type, ext) values ('application/vnd.mobius.mbk', 'mbk')
insert into mimetypes (mime_type, ext) values ('application/vnd.mobius.mqy', 'mqy')
insert into mimetypes (mime_type, ext) values ('application/vnd.mobius.msl', 'msl')
insert into mimetypes (mime_type, ext) values ('application/vnd.mobius.plc', 'plc')
insert into mimetypes (mime_type, ext) values ('application/vnd.mobius.txf', 'txf')
insert into mimetypes (mime_type, ext) values ('application/vnd.mophun.application', 'mpn')
insert into mimetypes (mime_type, ext) values ('application/vnd.mophun.certificate', 'mpc')
insert into mimetypes (mime_type, ext) values ('application/vnd.mozilla.xul+xml', 'xul')
insert into mimetypes (mime_type, ext) values ('application/vnd.ms-artgalry', 'cil')
insert into mimetypes (mime_type, ext) values ('application/vnd.ms-cab-compressed', 'cab')
insert into mimetypes (mime_type, ext) values ('application/vnd.ms-excel', 'xls xlm xla xlc xlt xlw')
insert into mimetypes (mime_type, ext) values ('application/vnd.ms-excel.addin.macroenabled.12', 'xlam')
insert into mimetypes (mime_type, ext) values ('application/vnd.ms-excel.sheet.binary.macroenabled.12', 'xlsb')
insert into mimetypes (mime_type, ext) values ('application/vnd.ms-excel.sheet.macroenabled.12', 'xlsm')
insert into mimetypes (mime_type, ext) values ('application/vnd.ms-excel.template.macroenabled.12', 'xltm')
insert into mimetypes (mime_type, ext) values ('application/vnd.ms-fontobject', 'eot')
insert into mimetypes (mime_type, ext) values ('application/vnd.ms-htmlhelp', 'chm')
insert into mimetypes (mime_type, ext) values ('application/vnd.ms-ims', 'ims')
insert into mimetypes (mime_type, ext) values ('application/vnd.ms-lrm', 'lrm')
insert into mimetypes (mime_type, ext) values ('application/vnd.ms-officetheme', 'thmx')
insert into mimetypes (mime_type, ext) values ('application/vnd.ms-pki.seccat', 'cat')
insert into mimetypes (mime_type, ext) values ('application/vnd.ms-pki.stl', 'stl')
insert into mimetypes (mime_type, ext) values ('application/vnd.ms-powerpoint', 'ppt pps pot')
insert into mimetypes (mime_type, ext) values ('application/vnd.ms-powerpoint.addin.macroenabled.12', 'ppam')
insert into mimetypes (mime_type, ext) values ('application/vnd.ms-powerpoint.presentation.macroenabled.12', 'pptm')
insert into mimetypes (mime_type, ext) values ('application/vnd.ms-powerpoint.slide.macroenabled.12', 'sldm')
insert into mimetypes (mime_type, ext) values ('application/vnd.ms-powerpoint.slideshow.macroenabled.12', 'ppsm')
insert into mimetypes (mime_type, ext) values ('application/vnd.ms-powerpoint.template.macroenabled.12', 'potm')
insert into mimetypes (mime_type, ext) values ('application/vnd.ms-project', 'mpp mpt')
insert into mimetypes (mime_type, ext) values ('application/vnd.ms-word.document.macroenabled.12', 'docm')
insert into mimetypes (mime_type, ext) values ('application/vnd.ms-word.template.macroenabled.12', 'dotm')
insert into mimetypes (mime_type, ext) values ('application/vnd.ms-works', 'wps wks wcm wdb')
insert into mimetypes (mime_type, ext) values ('application/vnd.ms-wpl', 'wpl')
insert into mimetypes (mime_type, ext) values ('application/vnd.ms-xpsdocument', 'xps')
insert into mimetypes (mime_type, ext) values ('application/vnd.mseq', 'mseq')
insert into mimetypes (mime_type, ext) values ('application/vnd.musician', 'mus')
insert into mimetypes (mime_type, ext) values ('application/vnd.muvee.style', 'msty')
insert into mimetypes (mime_type, ext) values ('application/vnd.mynfc', 'taglet')
insert into mimetypes (mime_type, ext) values ('application/vnd.neurolanguage.nlu', 'nlu')
insert into mimetypes (mime_type, ext) values ('application/vnd.nitf', 'ntf nitf')
insert into mimetypes (mime_type, ext) values ('application/vnd.noblenet-directory', 'nnd')
insert into mimetypes (mime_type, ext) values ('application/vnd.noblenet-sealer', 'nns')
insert into mimetypes (mime_type, ext) values ('application/vnd.noblenet-web', 'nnw')
insert into mimetypes (mime_type, ext) values ('application/vnd.nokia.n-gage.data', 'ngdat')
insert into mimetypes (mime_type, ext) values ('application/vnd.nokia.n-gage.symbian.install', 'n-gage')
insert into mimetypes (mime_type, ext) values ('application/vnd.nokia.radio-preset', 'rpst')
insert into mimetypes (mime_type, ext) values ('application/vnd.nokia.radio-presets', 'rpss')
insert into mimetypes (mime_type, ext) values ('application/vnd.novadigm.edm', 'edm')
insert into mimetypes (mime_type, ext) values ('application/vnd.novadigm.edx', 'edx')
insert into mimetypes (mime_type, ext) values ('application/vnd.novadigm.ext', 'ext')
insert into mimetypes (mime_type, ext) values ('application/vnd.oasis.opendocument.chart', 'odc')
insert into mimetypes (mime_type, ext) values ('application/vnd.oasis.opendocument.chart-template', 'otc')
insert into mimetypes (mime_type, ext) values ('application/vnd.oasis.opendocument.database', 'odb')
insert into mimetypes (mime_type, ext) values ('application/vnd.oasis.opendocument.formula', 'odf')
insert into mimetypes (mime_type, ext) values ('application/vnd.oasis.opendocument.formula-template', 'odft')
insert into mimetypes (mime_type, ext) values ('application/vnd.oasis.opendocument.graphics', 'odg')
insert into mimetypes (mime_type, ext) values ('application/vnd.oasis.opendocument.graphics-template', 'otg')
insert into mimetypes (mime_type, ext) values ('application/vnd.oasis.opendocument.image', 'odi')
insert into mimetypes (mime_type, ext) values ('application/vnd.oasis.opendocument.image-template', 'oti')
insert into mimetypes (mime_type, ext) values ('application/vnd.oasis.opendocument.presentation', 'odp')
insert into mimetypes (mime_type, ext) values ('application/vnd.oasis.opendocument.presentation-template', 'otp')
insert into mimetypes (mime_type, ext) values ('application/vnd.oasis.opendocument.spreadsheet', 'ods')
insert into mimetypes (mime_type, ext) values ('application/vnd.oasis.opendocument.spreadsheet-template', 'ots')
insert into mimetypes (mime_type, ext) values ('application/vnd.oasis.opendocument.text', 'odt')
insert into mimetypes (mime_type, ext) values ('application/vnd.oasis.opendocument.text-master', 'odm')
insert into mimetypes (mime_type, ext) values ('application/vnd.oasis.opendocument.text-template', 'ott')
insert into mimetypes (mime_type, ext) values ('application/vnd.oasis.opendocument.text-web', 'oth')
insert into mimetypes (mime_type, ext) values ('application/vnd.olpc-sugar', 'xo')
insert into mimetypes (mime_type, ext) values ('application/vnd.oma.dd2+xml', 'dd2')
insert into mimetypes (mime_type, ext) values ('application/vnd.openofficeorg.extension', 'oxt')
insert into mimetypes (mime_type, ext) values ('application/vnd.openxmlformats-officedocument.presentationml.presentation', 'pptx')
insert into mimetypes (mime_type, ext) values ('application/vnd.openxmlformats-officedocument.presentationml.slide', 'sldx')
insert into mimetypes (mime_type, ext) values ('application/vnd.openxmlformats-officedocument.presentationml.slideshow', 'ppsx')
insert into mimetypes (mime_type, ext) values ('application/vnd.openxmlformats-officedocument.presentationml.template', 'potx')
insert into mimetypes (mime_type, ext) values ('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'xlsx')
insert into mimetypes (mime_type, ext) values ('application/vnd.openxmlformats-officedocument.spreadsheetml.template', 'xltx')
insert into mimetypes (mime_type, ext) values ('application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'docx')
insert into mimetypes (mime_type, ext) values ('application/vnd.openxmlformats-officedocument.wordprocessingml.template', 'dotx')
insert into mimetypes (mime_type, ext) values ('application/vnd.osgeo.mapguide.package', 'mgp')
insert into mimetypes (mime_type, ext) values ('application/vnd.osgi.dp', 'dp')
insert into mimetypes (mime_type, ext) values ('application/vnd.osgi.subsystem', 'esa')
insert into mimetypes (mime_type, ext) values ('application/vnd.palm', 'pdb pqa oprc')
insert into mimetypes (mime_type, ext) values ('application/vnd.pawaafile', 'paw')
insert into mimetypes (mime_type, ext) values ('application/vnd.pg.format', 'str')
insert into mimetypes (mime_type, ext) values ('application/vnd.pg.osasli', 'ei6')
insert into mimetypes (mime_type, ext) values ('application/vnd.picsel', 'efif')
insert into mimetypes (mime_type, ext) values ('application/vnd.pmi.widget', 'wg')
insert into mimetypes (mime_type, ext) values ('application/vnd.pocketlearn', 'plf')
insert into mimetypes (mime_type, ext) values ('application/vnd.powerbuilder6', 'pbd')
insert into mimetypes (mime_type, ext) values ('application/vnd.previewsystems.box', 'box')
insert into mimetypes (mime_type, ext) values ('application/vnd.proteus.magazine', 'mgz')
insert into mimetypes (mime_type, ext) values ('application/vnd.publishare-delta-tree', 'qps')
insert into mimetypes (mime_type, ext) values ('application/vnd.pvi.ptid1', 'ptid')
insert into mimetypes (mime_type, ext) values ('application/vnd.quark.quarkxpress', 'qxd qxt qwd qwt qxl qxb')
insert into mimetypes (mime_type, ext) values ('application/vnd.realvnc.bed', 'bed')
insert into mimetypes (mime_type, ext) values ('application/vnd.recordare.musicxml', 'mxl')
insert into mimetypes (mime_type, ext) values ('application/vnd.recordare.musicxml+xml', 'musicxml')
insert into mimetypes (mime_type, ext) values ('application/vnd.rig.cryptonote', 'cryptonote')
insert into mimetypes (mime_type, ext) values ('application/vnd.rim.cod', 'cod')
insert into mimetypes (mime_type, ext) values ('application/vnd.rn-realmedia', 'rm')
insert into mimetypes (mime_type, ext) values ('application/vnd.rn-realmedia-vbr', 'rmvb')
insert into mimetypes (mime_type, ext) values ('application/vnd.route66.link66+xml', 'link66')
insert into mimetypes (mime_type, ext) values ('application/vnd.sailingtracker.track', 'st')
insert into mimetypes (mime_type, ext) values ('application/vnd.seemail', 'see')
insert into mimetypes (mime_type, ext) values ('application/vnd.sema', 'sema')
insert into mimetypes (mime_type, ext) values ('application/vnd.semd', 'semd')
insert into mimetypes (mime_type, ext) values ('application/vnd.semf', 'semf')
insert into mimetypes (mime_type, ext) values ('application/vnd.shana.informed.formdata', 'ifm')
insert into mimetypes (mime_type, ext) values ('application/vnd.shana.informed.formtemplate', 'itp')
insert into mimetypes (mime_type, ext) values ('application/vnd.shana.informed.interchange', 'iif')
insert into mimetypes (mime_type, ext) values ('application/vnd.shana.informed.package', 'ipk')
insert into mimetypes (mime_type, ext) values ('application/vnd.simtech-mindmapper', 'twd twds')
insert into mimetypes (mime_type, ext) values ('application/vnd.smaf', 'mmf')
insert into mimetypes (mime_type, ext) values ('application/vnd.smart.teacher', 'teacher')
insert into mimetypes (mime_type, ext) values ('application/vnd.solent.sdkm+xml', 'sdkm sdkd')
insert into mimetypes (mime_type, ext) values ('application/vnd.spotfire.dxp', 'dxp')
insert into mimetypes (mime_type, ext) values ('application/vnd.spotfire.sfs', 'sfs')
insert into mimetypes (mime_type, ext) values ('application/vnd.stardivision.calc', 'sdc')
insert into mimetypes (mime_type, ext) values ('application/vnd.stardivision.draw', 'sda')
insert into mimetypes (mime_type, ext) values ('application/vnd.stardivision.impress', 'sdd')
insert into mimetypes (mime_type, ext) values ('application/vnd.stardivision.math', 'smf')
insert into mimetypes (mime_type, ext) values ('application/vnd.stardivision.writer', 'sdw vor')
insert into mimetypes (mime_type, ext) values ('application/vnd.stardivision.writer-global', 'sgl')
insert into mimetypes (mime_type, ext) values ('application/vnd.stepmania.package', 'smzip')
insert into mimetypes (mime_type, ext) values ('application/vnd.stepmania.stepchart', 'sm')
insert into mimetypes (mime_type, ext) values ('application/vnd.sun.xml.calc', 'sxc')
insert into mimetypes (mime_type, ext) values ('application/vnd.sun.xml.calc.template', 'stc')
insert into mimetypes (mime_type, ext) values ('application/vnd.sun.xml.draw', 'sxd')
insert into mimetypes (mime_type, ext) values ('application/vnd.sun.xml.draw.template', 'std')
insert into mimetypes (mime_type, ext) values ('application/vnd.sun.xml.impress', 'sxi')
insert into mimetypes (mime_type, ext) values ('application/vnd.sun.xml.impress.template', 'sti')
insert into mimetypes (mime_type, ext) values ('application/vnd.sun.xml.math', 'sxm')
insert into mimetypes (mime_type, ext) values ('application/vnd.sun.xml.writer', 'sxw')
insert into mimetypes (mime_type, ext) values ('application/vnd.sun.xml.writer.global', 'sxg')
insert into mimetypes (mime_type, ext) values ('application/vnd.sun.xml.writer.template', 'stw')
insert into mimetypes (mime_type, ext) values ('application/vnd.sus-calendar', 'sus susp')
insert into mimetypes (mime_type, ext) values ('application/vnd.svd', 'svd')
insert into mimetypes (mime_type, ext) values ('application/vnd.symbian.install', 'sis sisx')
insert into mimetypes (mime_type, ext) values ('application/vnd.syncml+xml', 'xsm')
insert into mimetypes (mime_type, ext) values ('application/vnd.syncml.dm+wbxml', 'bdm')
insert into mimetypes (mime_type, ext) values ('application/vnd.syncml.dm+xml', 'xdm')
insert into mimetypes (mime_type, ext) values ('application/vnd.tao.intent-module-archive', 'tao')
insert into mimetypes (mime_type, ext) values ('application/vnd.tcpdump.pcap', 'pcap cap dmp')
insert into mimetypes (mime_type, ext) values ('application/vnd.tmobile-livetv', 'tmo')
insert into mimetypes (mime_type, ext) values ('application/vnd.trid.tpt', 'tpt')
insert into mimetypes (mime_type, ext) values ('application/vnd.triscape.mxs', 'mxs')
insert into mimetypes (mime_type, ext) values ('application/vnd.trueapp', 'tra')
insert into mimetypes (mime_type, ext) values ('application/vnd.ufdl', 'ufd ufdl')
insert into mimetypes (mime_type, ext) values ('application/vnd.uiq.theme', 'utz')
insert into mimetypes (mime_type, ext) values ('application/vnd.umajin', 'umj')
insert into mimetypes (mime_type, ext) values ('application/vnd.unity', 'unityweb')
insert into mimetypes (mime_type, ext) values ('application/vnd.uoml+xml', 'uoml')
insert into mimetypes (mime_type, ext) values ('application/vnd.vcx', 'vcx')
insert into mimetypes (mime_type, ext) values ('application/vnd.visio', 'vsd vst vss vsw')
insert into mimetypes (mime_type, ext) values ('application/vnd.visionary', 'vis')
insert into mimetypes (mime_type, ext) values ('application/vnd.vsf', 'vsf')
insert into mimetypes (mime_type, ext) values ('application/vnd.wap.wbxml', 'wbxml')
insert into mimetypes (mime_type, ext) values ('application/vnd.wap.wmlc', 'wmlc')
insert into mimetypes (mime_type, ext) values ('application/vnd.wap.wmlscriptc', 'wmlsc')
insert into mimetypes (mime_type, ext) values ('application/vnd.webturbo', 'wtb')
insert into mimetypes (mime_type, ext) values ('application/vnd.wolfram.player', 'nbp')
insert into mimetypes (mime_type, ext) values ('application/vnd.wordperfect', 'wpd')
insert into mimetypes (mime_type, ext) values ('application/vnd.wqd', 'wqd')
insert into mimetypes (mime_type, ext) values ('application/vnd.wt.stf', 'stf')
insert into mimetypes (mime_type, ext) values ('application/vnd.xara', 'xar')
insert into mimetypes (mime_type, ext) values ('application/vnd.xfdl', 'xfdl')
insert into mimetypes (mime_type, ext) values ('application/vnd.yamaha.hv-dic', 'hvd')
insert into mimetypes (mime_type, ext) values ('application/vnd.yamaha.hv-script', 'hvs')
insert into mimetypes (mime_type, ext) values ('application/vnd.yamaha.hv-voice', 'hvp')
insert into mimetypes (mime_type, ext) values ('application/vnd.yamaha.openscoreformat', 'osf')
insert into mimetypes (mime_type, ext) values ('application/vnd.yamaha.openscoreformat.osfpvg+xml', 'osfpvg')
insert into mimetypes (mime_type, ext) values ('application/vnd.yamaha.smaf-audio', 'saf')
insert into mimetypes (mime_type, ext) values ('application/vnd.yamaha.smaf-phrase', 'spf')
insert into mimetypes (mime_type, ext) values ('application/vnd.yellowriver-custom-menu', 'cmp')
insert into mimetypes (mime_type, ext) values ('application/vnd.zul', 'zir zirz')
insert into mimetypes (mime_type, ext) values ('application/vnd.zzazz.deck+xml', 'zaz')
insert into mimetypes (mime_type, ext) values ('application/voicexml+xml', 'vxml')
insert into mimetypes (mime_type, ext) values ('application/widget', 'wgt')
insert into mimetypes (mime_type, ext) values ('application/winhlp', 'hlp')
insert into mimetypes (mime_type, ext) values ('application/wsdl+xml', 'wsdl')
insert into mimetypes (mime_type, ext) values ('application/wspolicy+xml', 'wspolicy')
insert into mimetypes (mime_type, ext) values ('application/x-7z-compressed', '7z')
insert into mimetypes (mime_type, ext) values ('application/x-abiword', 'abw')
insert into mimetypes (mime_type, ext) values ('application/x-ace-compressed', 'ace')
insert into mimetypes (mime_type, ext) values ('application/x-apple-diskimage', 'dmg')
insert into mimetypes (mime_type, ext) values ('application/x-authorware-bin', 'aab x32 u32 vox')
insert into mimetypes (mime_type, ext) values ('application/x-authorware-map', 'aam')
insert into mimetypes (mime_type, ext) values ('application/x-authorware-seg', 'aas')
insert into mimetypes (mime_type, ext) values ('application/x-bcpio', 'bcpio')
insert into mimetypes (mime_type, ext) values ('application/x-bittorrent', 'torrent')
insert into mimetypes (mime_type, ext) values ('application/x-blorb', 'blb blorb')
insert into mimetypes (mime_type, ext) values ('application/x-bzip', 'bz')
insert into mimetypes (mime_type, ext) values ('application/x-bzip2', 'bz2 boz')
insert into mimetypes (mime_type, ext) values ('application/x-cbr', 'cbr cba cbt cbz cb7')
insert into mimetypes (mime_type, ext) values ('application/x-cdlink', 'vcd')
insert into mimetypes (mime_type, ext) values ('application/x-cfs-compressed', 'cfs')
insert into mimetypes (mime_type, ext) values ('application/x-chat', 'chat')
insert into mimetypes (mime_type, ext) values ('application/x-chess-pgn', 'pgn')
insert into mimetypes (mime_type, ext) values ('application/x-conference', 'nsc')
insert into mimetypes (mime_type, ext) values ('application/x-cpio', 'cpio')
insert into mimetypes (mime_type, ext) values ('application/x-csh', 'csh')
insert into mimetypes (mime_type, ext) values ('application/x-debian-package', 'deb udeb')
insert into mimetypes (mime_type, ext) values ('application/x-dgc-compressed', 'dgc')
insert into mimetypes (mime_type, ext) values ('application/x-director', 'dir dcr dxr cst cct cxt w3d fgd swa')
insert into mimetypes (mime_type, ext) values ('application/x-doom', 'wad')
insert into mimetypes (mime_type, ext) values ('application/x-dtbncx+xml', 'ncx')
insert into mimetypes (mime_type, ext) values ('application/x-dtbook+xml', 'dtb')
insert into mimetypes (mime_type, ext) values ('application/x-dtbresource+xml', 'res')
insert into mimetypes (mime_type, ext) values ('application/x-dvi', 'dvi')
insert into mimetypes (mime_type, ext) values ('application/x-envoy', 'evy')
insert into mimetypes (mime_type, ext) values ('application/x-eva', 'eva')
insert into mimetypes (mime_type, ext) values ('application/x-font-bdf', 'bdf')
insert into mimetypes (mime_type, ext) values ('application/x-font-ghostscript', 'gsf')
insert into mimetypes (mime_type, ext) values ('application/x-font-linux-psf', 'psf')
insert into mimetypes (mime_type, ext) values ('application/x-font-otf', 'otf')
insert into mimetypes (mime_type, ext) values ('application/x-font-pcf', 'pcf')
insert into mimetypes (mime_type, ext) values ('application/x-font-snf', 'snf')
insert into mimetypes (mime_type, ext) values ('application/x-font-ttf', 'ttf ttc')
insert into mimetypes (mime_type, ext) values ('application/x-font-type1', 'pfa pfb pfm afm')
insert into mimetypes (mime_type, ext) values ('application/x-font-woff', 'woff')
insert into mimetypes (mime_type, ext) values ('application/x-freearc', 'arc')
insert into mimetypes (mime_type, ext) values ('application/x-futuresplash', 'spl')
insert into mimetypes (mime_type, ext) values ('application/x-gca-compressed', 'gca')
insert into mimetypes (mime_type, ext) values ('application/x-glulx', 'ulx')
insert into mimetypes (mime_type, ext) values ('application/x-gnumeric', 'gnumeric')
insert into mimetypes (mime_type, ext) values ('application/x-gramps-xml', 'gramps')
insert into mimetypes (mime_type, ext) values ('application/x-gtar', 'gtar')
insert into mimetypes (mime_type, ext) values ('application/x-hdf', 'hdf')
insert into mimetypes (mime_type, ext) values ('application/x-install-instructions', 'install')
insert into mimetypes (mime_type, ext) values ('application/x-iso9660-image', 'iso')
insert into mimetypes (mime_type, ext) values ('application/x-java-jnlp-file', 'jnlp')
insert into mimetypes (mime_type, ext) values ('application/x-latex', 'latex')
insert into mimetypes (mime_type, ext) values ('application/x-lzh-compressed', 'lzh lha')
insert into mimetypes (mime_type, ext) values ('application/x-mie', 'mie')
insert into mimetypes (mime_type, ext) values ('application/x-mobipocket-ebook', 'prc mobi')
insert into mimetypes (mime_type, ext) values ('application/x-ms-application', 'application')
insert into mimetypes (mime_type, ext) values ('application/x-ms-shortcut', 'lnk')
insert into mimetypes (mime_type, ext) values ('application/x-ms-wmd', 'wmd')
insert into mimetypes (mime_type, ext) values ('application/x-ms-wmz', 'wmz')
insert into mimetypes (mime_type, ext) values ('application/x-ms-xbap', 'xbap')
insert into mimetypes (mime_type, ext) values ('application/x-msaccess', 'mdb')
insert into mimetypes (mime_type, ext) values ('application/x-msbinder', 'obd')
insert into mimetypes (mime_type, ext) values ('application/x-mscardfile', 'crd')
insert into mimetypes (mime_type, ext) values ('application/x-msclip', 'clp')
insert into mimetypes (mime_type, ext) values ('application/x-msdownload', 'exe dll com bat msi')
insert into mimetypes (mime_type, ext) values ('application/x-msmediaview', 'mvb m13 m14')
insert into mimetypes (mime_type, ext) values ('application/x-msmetafile', 'wmf wmz emf emz')
insert into mimetypes (mime_type, ext) values ('application/x-msmoney', 'mny')
insert into mimetypes (mime_type, ext) values ('application/x-mspublisher', 'pub')
insert into mimetypes (mime_type, ext) values ('application/x-msschedule', 'scd')
insert into mimetypes (mime_type, ext) values ('application/x-msterminal', 'trm')
insert into mimetypes (mime_type, ext) values ('application/x-mswrite', 'wri')
insert into mimetypes (mime_type, ext) values ('application/x-netcdf', 'nc cdf')
insert into mimetypes (mime_type, ext) values ('application/x-nzb', 'nzb')
insert into mimetypes (mime_type, ext) values ('application/x-pkcs12', 'p12 pfx')
insert into mimetypes (mime_type, ext) values ('application/x-pkcs7-certificates', 'p7b spc')
insert into mimetypes (mime_type, ext) values ('application/x-pkcs7-certreqresp', 'p7r')
insert into mimetypes (mime_type, ext) values ('application/x-rar-compressed', 'rar')
insert into mimetypes (mime_type, ext) values ('application/x-research-info-systems', 'ris')
insert into mimetypes (mime_type, ext) values ('application/x-sh', 'sh')
insert into mimetypes (mime_type, ext) values ('application/x-shar', 'shar')
insert into mimetypes (mime_type, ext) values ('application/x-shockwave-flash', 'swf')
insert into mimetypes (mime_type, ext) values ('application/x-silverlight-app', 'xap')
insert into mimetypes (mime_type, ext) values ('application/x-sql', 'sql')
insert into mimetypes (mime_type, ext) values ('application/x-stuffit', 'sit')
insert into mimetypes (mime_type, ext) values ('application/x-stuffitx', 'sitx')
insert into mimetypes (mime_type, ext) values ('application/x-subrip', 'srt')
insert into mimetypes (mime_type, ext) values ('application/x-sv4cpio', 'sv4cpio')
insert into mimetypes (mime_type, ext) values ('application/x-sv4crc', 'sv4crc')
insert into mimetypes (mime_type, ext) values ('application/x-t3vm-image', 't3')
insert into mimetypes (mime_type, ext) values ('application/x-tads', 'gam')
insert into mimetypes (mime_type, ext) values ('application/x-tar', 'tar')
insert into mimetypes (mime_type, ext) values ('application/x-tcl', 'tcl')
insert into mimetypes (mime_type, ext) values ('application/x-tex', 'tex')
insert into mimetypes (mime_type, ext) values ('application/x-tex-tfm', 'tfm')
insert into mimetypes (mime_type, ext) values ('application/x-texinfo', 'texinfo texi')
insert into mimetypes (mime_type, ext) values ('application/x-tgif', 'obj')
insert into mimetypes (mime_type, ext) values ('application/x-ustar', 'ustar')
insert into mimetypes (mime_type, ext) values ('application/x-wais-source', 'src')
insert into mimetypes (mime_type, ext) values ('application/x-x509-ca-cert', 'der crt')
insert into mimetypes (mime_type, ext) values ('application/x-xfig', 'fig')
insert into mimetypes (mime_type, ext) values ('application/x-xliff+xml', 'xlf')
insert into mimetypes (mime_type, ext) values ('application/x-xpinstall', 'xpi')
insert into mimetypes (mime_type, ext) values ('application/x-xz', 'xz')
insert into mimetypes (mime_type, ext) values ('application/x-zmachine', 'z1 z2 z3 z4 z5 z6 z7 z8')
insert into mimetypes (mime_type, ext) values ('application/xaml+xml', 'xaml')
insert into mimetypes (mime_type, ext) values ('application/xcap-diff+xml', 'xdf')
insert into mimetypes (mime_type, ext) values ('application/xenc+xml', 'xenc')
insert into mimetypes (mime_type, ext) values ('application/xhtml+xml', 'xhtml xht')
insert into mimetypes (mime_type, ext) values ('application/xml', 'xml xsl')
insert into mimetypes (mime_type, ext) values ('application/xml-dtd', 'dtd')
insert into mimetypes (mime_type, ext) values ('application/xop+xml', 'xop')
insert into mimetypes (mime_type, ext) values ('application/xproc+xml', 'xpl')
insert into mimetypes (mime_type, ext) values ('application/xslt+xml', 'xslt')
insert into mimetypes (mime_type, ext) values ('application/xspf+xml', 'xspf')
insert into mimetypes (mime_type, ext) values ('application/xv+xml', 'mxml xhvml xvml xvm')
insert into mimetypes (mime_type, ext) values ('application/yang', 'yang')
insert into mimetypes (mime_type, ext) values ('application/yin+xml', 'yin')
insert into mimetypes (mime_type, ext) values ('application/zip', 'zip')
insert into mimetypes (mime_type, ext) values ('audio/adpcm', 'adp')
insert into mimetypes (mime_type, ext) values ('audio/basic', 'au snd')
insert into mimetypes (mime_type, ext) values ('audio/midi', 'mid midi kar rmi')
insert into mimetypes (mime_type, ext) values ('audio/mp4', 'mp4a')
insert into mimetypes (mime_type, ext) values ('audio/mpeg', 'mpga mp2 mp2a mp3 m2a m3a')
insert into mimetypes (mime_type, ext) values ('audio/ogg', 'oga ogg spx')
insert into mimetypes (mime_type, ext) values ('audio/s3m', 's3m')
insert into mimetypes (mime_type, ext) values ('audio/silk', 'sil')
insert into mimetypes (mime_type, ext) values ('audio/vnd.dece.audio', 'uva uvva')
insert into mimetypes (mime_type, ext) values ('audio/vnd.digital-winds', 'eol')
insert into mimetypes (mime_type, ext) values ('audio/vnd.dra', 'dra')
insert into mimetypes (mime_type, ext) values ('audio/vnd.dts', 'dts')
insert into mimetypes (mime_type, ext) values ('audio/vnd.dts.hd', 'dtshd')
insert into mimetypes (mime_type, ext) values ('audio/vnd.lucent.voice', 'lvp')
insert into mimetypes (mime_type, ext) values ('audio/vnd.ms-playready.media.pya', 'pya')
insert into mimetypes (mime_type, ext) values ('audio/vnd.nuera.ecelp4800', 'ecelp4800')
insert into mimetypes (mime_type, ext) values ('audio/vnd.nuera.ecelp7470', 'ecelp7470')
insert into mimetypes (mime_type, ext) values ('audio/vnd.nuera.ecelp9600', 'ecelp9600')
insert into mimetypes (mime_type, ext) values ('audio/vnd.rip', 'rip')
insert into mimetypes (mime_type, ext) values ('audio/webm', 'weba')
insert into mimetypes (mime_type, ext) values ('audio/x-aac', 'aac')
insert into mimetypes (mime_type, ext) values ('audio/x-aiff', 'aif aiff aifc')
insert into mimetypes (mime_type, ext) values ('audio/x-caf', 'caf')
insert into mimetypes (mime_type, ext) values ('audio/x-flac', 'flac')
insert into mimetypes (mime_type, ext) values ('audio/x-matroska', 'mka')
insert into mimetypes (mime_type, ext) values ('audio/x-mpegurl', 'm3u')
insert into mimetypes (mime_type, ext) values ('audio/x-ms-wax', 'wax')
insert into mimetypes (mime_type, ext) values ('audio/x-ms-wma', 'wma')
insert into mimetypes (mime_type, ext) values ('audio/x-pn-realaudio', 'ram ra')
insert into mimetypes (mime_type, ext) values ('audio/x-pn-realaudio-plugin', 'rmp')
insert into mimetypes (mime_type, ext) values ('audio/x-wav', 'wav')
insert into mimetypes (mime_type, ext) values ('audio/xm', 'xm')
insert into mimetypes (mime_type, ext) values ('chemical/x-cdx', 'cdx')
insert into mimetypes (mime_type, ext) values ('chemical/x-cif', 'cif')
insert into mimetypes (mime_type, ext) values ('chemical/x-cmdf', 'cmdf')
insert into mimetypes (mime_type, ext) values ('chemical/x-cml', 'cml')
insert into mimetypes (mime_type, ext) values ('chemical/x-csml', 'csml')
insert into mimetypes (mime_type, ext) values ('chemical/x-xyz', 'xyz')
insert into mimetypes (mime_type, ext) values ('image/bmp', 'bmp')
insert into mimetypes (mime_type, ext) values ('image/cgm', 'cgm')
insert into mimetypes (mime_type, ext) values ('image/g3fax', 'g3')
insert into mimetypes (mime_type, ext) values ('image/gif', 'gif')
insert into mimetypes (mime_type, ext) values ('image/ief', 'ief')
insert into mimetypes (mime_type, ext) values ('image/jpeg', 'jpeg jpg jpe')
insert into mimetypes (mime_type, ext) values ('image/ktx', 'ktx')
insert into mimetypes (mime_type, ext) values ('image/png', 'png')
insert into mimetypes (mime_type, ext) values ('image/prs.btif', 'btif')
insert into mimetypes (mime_type, ext) values ('image/sgi', 'sgi')
insert into mimetypes (mime_type, ext) values ('image/svg+xml', 'svg svgz')
insert into mimetypes (mime_type, ext) values ('image/tiff', 'tiff tif')
insert into mimetypes (mime_type, ext) values ('image/vnd.adobe.photoshop', 'psd')
insert into mimetypes (mime_type, ext) values ('image/vnd.dece.graphic', 'uvi uvvi uvg uvvg')
insert into mimetypes (mime_type, ext) values ('image/vnd.dvb.subtitle', 'sub')
insert into mimetypes (mime_type, ext) values ('image/vnd.djvu', 'djvu djv')
insert into mimetypes (mime_type, ext) values ('image/vnd.dwg', 'dwg')
insert into mimetypes (mime_type, ext) values ('image/vnd.dxf', 'dxf')
insert into mimetypes (mime_type, ext) values ('image/vnd.fastbidsheet', 'fbs')
insert into mimetypes (mime_type, ext) values ('image/vnd.fpx', 'fpx')
insert into mimetypes (mime_type, ext) values ('image/vnd.fst', 'fst')
insert into mimetypes (mime_type, ext) values ('image/vnd.fujixerox.edmics-mmr', 'mmr')
insert into mimetypes (mime_type, ext) values ('image/vnd.fujixerox.edmics-rlc', 'rlc')
insert into mimetypes (mime_type, ext) values ('image/vnd.ms-modi', 'mdi')
insert into mimetypes (mime_type, ext) values ('image/vnd.ms-photo', 'wdp')
insert into mimetypes (mime_type, ext) values ('image/vnd.net-fpx', 'npx')
insert into mimetypes (mime_type, ext) values ('image/vnd.wap.wbmp', 'wbmp')
insert into mimetypes (mime_type, ext) values ('image/vnd.xiff', 'xif')
insert into mimetypes (mime_type, ext) values ('image/webp', 'webp')
insert into mimetypes (mime_type, ext) values ('image/x-3ds', '3ds')
insert into mimetypes (mime_type, ext) values ('image/x-cmu-raster', 'ras')
insert into mimetypes (mime_type, ext) values ('image/x-cmx', 'cmx')
insert into mimetypes (mime_type, ext) values ('image/x-freehand', 'fh fhc fh4 fh5 fh7')
insert into mimetypes (mime_type, ext) values ('image/x-icon', 'ico')
insert into mimetypes (mime_type, ext) values ('image/x-mrsid-image', 'sid')
insert into mimetypes (mime_type, ext) values ('image/x-pcx', 'pcx')
insert into mimetypes (mime_type, ext) values ('image/x-pict', 'pic pct')
insert into mimetypes (mime_type, ext) values ('image/x-portable-anymap', 'pnm')
insert into mimetypes (mime_type, ext) values ('image/x-portable-bitmap', 'pbm')
insert into mimetypes (mime_type, ext) values ('image/x-portable-graymap', 'pgm')
insert into mimetypes (mime_type, ext) values ('image/x-portable-pixmap', 'ppm')
insert into mimetypes (mime_type, ext) values ('image/x-rgb', 'rgb')
insert into mimetypes (mime_type, ext) values ('image/x-tga', 'tga')
insert into mimetypes (mime_type, ext) values ('image/x-xbitmap', 'xbm')
insert into mimetypes (mime_type, ext) values ('image/x-xpixmap', 'xpm')
insert into mimetypes (mime_type, ext) values ('image/x-xwindowdump', 'xwd')
insert into mimetypes (mime_type, ext) values ('message/rfc822', 'eml mime')
insert into mimetypes (mime_type, ext) values ('model/iges', 'igs iges')
insert into mimetypes (mime_type, ext) values ('model/mesh', 'msh mesh silo')
insert into mimetypes (mime_type, ext) values ('model/vnd.collada+xml', 'dae')
insert into mimetypes (mime_type, ext) values ('model/vnd.dwf', 'dwf')
insert into mimetypes (mime_type, ext) values ('model/vnd.gdl', 'gdl')
insert into mimetypes (mime_type, ext) values ('model/vnd.gtw', 'gtw')
insert into mimetypes (mime_type, ext) values ('model/vnd.mts', 'mts')
insert into mimetypes (mime_type, ext) values ('model/vnd.vtu', 'vtu')
insert into mimetypes (mime_type, ext) values ('model/vrml', 'wrl vrml')
insert into mimetypes (mime_type, ext) values ('model/x3d+binary', 'x3db x3dbz')
insert into mimetypes (mime_type, ext) values ('model/x3d+vrml', 'x3dv x3dvz')
insert into mimetypes (mime_type, ext) values ('model/x3d+xml', 'x3d x3dz')
insert into mimetypes (mime_type, ext) values ('text/cache-manifest', 'appcache')
insert into mimetypes (mime_type, ext) values ('text/calendar', 'ics ifb')
insert into mimetypes (mime_type, ext) values ('text/css', 'css')
insert into mimetypes (mime_type, ext) values ('text/csv', 'csv')
insert into mimetypes (mime_type, ext) values ('text/html', 'html htm')
insert into mimetypes (mime_type, ext) values ('text/n3', 'n3')
insert into mimetypes (mime_type, ext) values ('text/plain', 'txt text conf def list log in')
insert into mimetypes (mime_type, ext) values ('text/prs.lines.tag', 'dsc')
insert into mimetypes (mime_type, ext) values ('text/richtext', 'rtx')
insert into mimetypes (mime_type, ext) values ('text/sgml', 'sgml sgm')
insert into mimetypes (mime_type, ext) values ('text/tab-separated-values', 'tsv')
insert into mimetypes (mime_type, ext) values ('text/troff', 't tr roff man me ms')
insert into mimetypes (mime_type, ext) values ('text/turtle', 'ttl')
insert into mimetypes (mime_type, ext) values ('text/uri-list', 'uri uris urls')
insert into mimetypes (mime_type, ext) values ('text/vcard', 'vcard')
insert into mimetypes (mime_type, ext) values ('text/vnd.curl', 'curl')
insert into mimetypes (mime_type, ext) values ('text/vnd.curl.dcurl', 'dcurl')
insert into mimetypes (mime_type, ext) values ('text/vnd.curl.scurl', 'scurl')
insert into mimetypes (mime_type, ext) values ('text/vnd.curl.mcurl', 'mcurl')
insert into mimetypes (mime_type, ext) values ('text/vnd.dvb.subtitle', 'sub')
insert into mimetypes (mime_type, ext) values ('text/vnd.fly', 'fly')
insert into mimetypes (mime_type, ext) values ('text/vnd.fmi.flexstor', 'flx')
insert into mimetypes (mime_type, ext) values ('text/vnd.graphviz', 'gv')
insert into mimetypes (mime_type, ext) values ('text/vnd.in3d.3dml', '3dml')
insert into mimetypes (mime_type, ext) values ('text/vnd.in3d.spot', 'spot')
insert into mimetypes (mime_type, ext) values ('text/vnd.sun.j2me.app-descriptor', 'jad')
insert into mimetypes (mime_type, ext) values ('text/vnd.wap.wml', 'wml')
insert into mimetypes (mime_type, ext) values ('text/vnd.wap.wmlscript', 'wmls')
insert into mimetypes (mime_type, ext) values ('text/x-asm', 's asm')
insert into mimetypes (mime_type, ext) values ('text/x-c', 'c cc cxx cpp h hh dic')
insert into mimetypes (mime_type, ext) values ('text/x-fortran', 'f for f77 f90')
insert into mimetypes (mime_type, ext) values ('text/x-java-source', 'java')
insert into mimetypes (mime_type, ext) values ('text/x-opml', 'opml')
insert into mimetypes (mime_type, ext) values ('text/x-pascal', 'p pas')
insert into mimetypes (mime_type, ext) values ('text/x-nfo', 'nfo')
insert into mimetypes (mime_type, ext) values ('text/x-setext', 'etx')
insert into mimetypes (mime_type, ext) values ('text/x-sfv', 'sfv')
insert into mimetypes (mime_type, ext) values ('text/x-uuencode', 'uu')
insert into mimetypes (mime_type, ext) values ('text/x-vcalendar', 'vcs')
insert into mimetypes (mime_type, ext) values ('text/x-vcard', 'vcf')
insert into mimetypes (mime_type, ext) values ('video/3gpp', '3gp')
insert into mimetypes (mime_type, ext) values ('video/3gpp2', '3g2')
insert into mimetypes (mime_type, ext) values ('video/h261', 'h261')
insert into mimetypes (mime_type, ext) values ('video/h263', 'h263')
insert into mimetypes (mime_type, ext) values ('video/h264', 'h264')
insert into mimetypes (mime_type, ext) values ('video/jpeg', 'jpgv')
insert into mimetypes (mime_type, ext) values ('video/jpm', 'jpm jpgm')
insert into mimetypes (mime_type, ext) values ('video/mj2', 'mj2 mjp2')
insert into mimetypes (mime_type, ext) values ('video/mp4', 'mp4 mp4v mpg4')
insert into mimetypes (mime_type, ext) values ('video/mpeg', 'mpeg mpg mpe m1v m2v')
insert into mimetypes (mime_type, ext) values ('video/ogg', 'ogv')
insert into mimetypes (mime_type, ext) values ('video/quicktime', 'qt mov')
insert into mimetypes (mime_type, ext) values ('video/vnd.dece.hd', 'uvh uvvh')
insert into mimetypes (mime_type, ext) values ('video/vnd.dece.mobile', 'uvm uvvm')
insert into mimetypes (mime_type, ext) values ('video/vnd.dece.pd', 'uvp uvvp')
insert into mimetypes (mime_type, ext) values ('video/vnd.dece.sd', 'uvs uvvs')
insert into mimetypes (mime_type, ext) values ('video/vnd.dece.video', 'uvv uvvv')
insert into mimetypes (mime_type, ext) values ('video/vnd.dvb.file', 'dvb')
insert into mimetypes (mime_type, ext) values ('video/vnd.fvt', 'fvt')
insert into mimetypes (mime_type, ext) values ('video/vnd.mpegurl', 'mxu m4u')
insert into mimetypes (mime_type, ext) values ('video/vnd.ms-playready.media.pyv', 'pyv')
insert into mimetypes (mime_type, ext) values ('video/vnd.uvvu.mp4', 'uvu uvvu')
insert into mimetypes (mime_type, ext) values ('video/vnd.vivo', 'viv')
insert into mimetypes (mime_type, ext) values ('video/webm', 'webm')
insert into mimetypes (mime_type, ext) values ('video/x-f4v', 'f4v')
insert into mimetypes (mime_type, ext) values ('video/x-fli', 'fli')
insert into mimetypes (mime_type, ext) values ('video/x-flv', 'flv')
insert into mimetypes (mime_type, ext) values ('video/x-m4v', 'm4v')
insert into mimetypes (mime_type, ext) values ('video/x-matroska', 'mkv mk3d mks')
insert into mimetypes (mime_type, ext) values ('video/x-mng', 'mng')
insert into mimetypes (mime_type, ext) values ('video/x-ms-asf', 'asf asx')
insert into mimetypes (mime_type, ext) values ('video/x-ms-vob', 'vob')
insert into mimetypes (mime_type, ext) values ('video/x-ms-wm', 'wm')
insert into mimetypes (mime_type, ext) values ('video/x-ms-wmv', 'wmv')
insert into mimetypes (mime_type, ext) values ('video/x-ms-wmx', 'wmx')
insert into mimetypes (mime_type, ext) values ('video/x-ms-wvx', 'wvx')
insert into mimetypes (mime_type, ext) values ('video/x-msvideo', 'avi')
insert into mimetypes (mime_type, ext) values ('video/x-sgi-movie', 'movie')
insert into mimetypes (mime_type, ext) values ('video/x-smv', 'smv')
insert into mimetypes (mime_type, ext) values ('x-conference/x-cooltalk', 'ice')